[2022-01-24 18:41:10,856] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 18:41:10,872] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 18:41:10,872] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 18:41:10,872] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-24 18:41:10,872] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 18:41:10,888] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): del_invoice_staging> on 2022-01-01 00:00:00+00:00
[2022-01-24 18:41:10,893] {standard_task_runner.py:52} INFO - Started process 3516 to run task
[2022-01-24 18:41:10,896] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'datawarehouse_etl', 'del_invoice_staging', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/datawarehouse_***.py', '--cfg-path', '/tmp/tmp9qvfg5rh', '--error-file', '/tmp/tmppx06ulmr']
[2022-01-24 18:41:10,896] {standard_task_runner.py:77} INFO - Job 134: Subtask del_invoice_staging
[2022-01-24 18:41:10,950] {standard_task_runner.py:92} ERROR - Failed to execute job 134 for task del_invoice_staging
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 287, in task_run
    ti = _get_ti(task, args.execution_date_or_run_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 86, in _get_ti
    dag_run = _get_dag_run(task.dag, exec_date_or_run_id, create_if_necssary, session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 80, in _get_dag_run
    ) from None
airflow.exceptions.DagRunNotFound: DagRun for datawarehouse_etl with run_id or execution_date of 'scheduled__2022-01-01T00:00:00+00:00' not found
[2022-01-24 18:41:10,989] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-24 18:42:14,655] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 18:42:14,662] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [queued]>
[2022-01-24 18:42:14,662] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 18:42:14,662] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-24 18:42:14,662] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-24 18:42:14,671] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): del_invoice_staging> on 2022-01-01 00:00:00+00:00
[2022-01-24 18:42:14,675] {standard_task_runner.py:52} INFO - Started process 3580 to run task
[2022-01-24 18:42:14,677] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'datawarehouse_etl', 'del_invoice_staging', 'scheduled__2022-01-01T00:00:00+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/datawarehouse_***.py', '--cfg-path', '/tmp/tmpwob0tv_v', '--error-file', '/tmp/tmpxj9ii7xn']
[2022-01-24 18:42:14,678] {standard_task_runner.py:77} INFO - Job 140: Subtask del_invoice_staging
[2022-01-24 18:42:14,713] {logging_mixin.py:109} INFO - Running <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [running]> on host cd9bb47288d1
[2022-01-24 18:42:14,749] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=datawarehouse_etl
AIRFLOW_CTX_TASK_ID=del_invoice_staging
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-01T00:00:00+00:00
[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,750] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-24 18:42:14,751] {logging_mixin.py:109} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f76fb23ca90>, 'dag': <DAG: datawarehouse_etl>, 'dag_run': <DagRun datawarehouse_etl @ 2022-01-01 00:00:00+00:00: scheduled__2022-01-01T00:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2022, 1, 2, 0, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2022-01-01', 'ds_nodash': '20220101', 'execution_date': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'inlets': [], 'logical_date': DateTime(2022, 1, 1, 0, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2022-01-02', 'next_ds_nodash': '20220102', 'next_execution_date': DateTime(2022, 1, 2, 0, 0, 0, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2021-12-31', 'prev_ds_nodash': '20211231', 'prev_execution_date': datetime.datetime(2021, 12, 31, 0, 0, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'scheduled__2022-01-01T00:00:00+00:00', 'task': <Task(PythonOperator): del_invoice_staging>, 'task_instance': <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [running]>, 'task_instance_key_str': 'datawarehouse_etl__del_invoice_staging__20220101', 'test_mode': False, 'ti': <TaskInstance: datawarehouse_etl.del_invoice_staging scheduled__2022-01-01T00:00:00+00:00 [running]>, 'tomorrow_ds': '2022-01-02', 'tomorrow_ds_nodash': '20220102', 'ts': '2022-01-01T00:00:00+00:00', 'ts_nodash': '20220101T000000', 'ts_nodash_with_tz': '20220101T000000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2021-12-31', 'yesterday_ds_nodash': '20211231', 'key': 'value', 'ts_var': '2022-01-01T00:00:00+00:00', 'tsnodash_var': '20220101T000000', 'templates_dict': None}
[2022-01-24 18:42:14,758] {base.py:79} INFO - Using connection to: id: redshift. Host: tweet-data.ciyer0z3ifyd.us-east-2.redshift.amazonaws.com, Port: 5439, Schema: sales_dw, Login: awsuser, Password: ***, extra: {}
[2022-01-24 18:42:15,187] {logging_mixin.py:109} INFO - Object created.
[2022-01-24 18:42:15,420] {python.py:175} INFO - Done. Returned value was: None
[2022-01-24 18:42:15,481] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=datawarehouse_etl, task_id=del_invoice_staging, execution_date=20220101T000000, start_date=20220124T184214, end_date=20220124T184215
[2022-01-24 18:42:15,532] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-24 18:42:15,593] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
